name: "Ubuntu 22.04 Image"

on:
  workflow_dispatch:
  create:
    tags:
  push:
    paths:
      - 'Ubuntu-22.04/**'
  pull_request:
    paths:
      - 'Ubuntu-22.04/**'

jobs:
  Build_Image:
    uses: ./.github/workflows/build-image.yaml
    with:
      name: 'Ubuntu-22.04'
