name: "Ubuntu 22.04 Image"

on:
  push:
    tags:
      - '*'
    paths:
      - 'Ubuntu-22.04/**'
  pull_request:
    tags:
      - '*'
    paths:
      - 'Ubuntu-22.04/**'

jobs:
  Build_Image:
    uses: ./.github/workflows/build-image.yaml
    with:
      name: 'Ubuntu-22.04'
